### PR TITLE
Remove deprecated recurseDataGeneratorsForField

### PR DESCRIPTION
**Pull request by syndesis**
This was never officially supported but now throws a warning.  Apologies for the indentation/formatting changes from my editor.

### CODE REVIEW

**Comment by cdaringe** [comment]
This is awesome!  I need to install commitlint.  semantic release won't cut a release without a formatted commit.  Can you `git commit --amend` with a commit that reads `fix: remove deprecated recurseDataGeneratorsForField usage`?  Also, you could run `yarn format` too.  Apologies for not having ci catch that

**Comment by syndesis** [comment]
Sure, I'll add those now.

**Comment by syndesis** [comment]
Does that work or do I need to modify the first message?

**Comment by cdaringe** [comment]
I think we're set.  Thanks!

**Pull request merged**
